apiVersion: apps/v1

kind: Deployment

metadata:

  name: mariadb-deployment

spec:

  replicas: 1

  selector:

    matchLabels:

      app: mariadb

  template:

    metadata:

      labels:

        app: mariadb

    spec:

      containers:

      - name: mariadb

        image: hngtech11/mariadb:day1

        env:
          - name: MARIADB_USER

            valueFrom:

              configMapKeyRef:

                name: wordpress-config

                key: MARIADB_USER


          - name: MARIADB_PASSWORD

            valueFrom:

              secretKeyRef:

                name: wordpress-secrets

                key: MARIADB_PASSWORD



          - name: MARIADB_DATABASE

            valueFrom:

              configMapKeyRef:

                name: wordpress-config

                key: MARIADB_DATABASE
              
---
apiVersion: apps/v1

kind: Deployment

metadata:

  name: wordpress-deployment

spec:

  replicas: 1

  selector:

    matchLabels:

      app: wordpress

  template:

    metadata:

      labels:

        app: wordpress

    spec:

      containers:

      - name: wordpress

        image: hngtech11/wordpress:day1

        env:
          - name: WORDPRESS_DATABASE_USER

            valueFrom:

              configMapKeyRef:

                name: wordpress-config

                key: MARIADB_USER


          - name: WORDPRESS_DATABASE_PASSWORD

            valueFrom:

              secretKeyRef:

                name: wordpress-secrets

                key: MARIADB_PASSWORD



          - name: WORDPRESS_DATABASE_NAME

            valueFrom:

              configMapKeyRef:

                name: wordpress-config

                key: MARIADB_DATABASE
          - name: WORDPRESS_DATABASE_HOST

            value: "mariadb-service"


        ports:

          - containerPort: 8443

          - containerPort: 8080

---
apiVersion: v1

kind: Service

metadata:

  name: wordpress-service

spec:

  type: NodePort

  selector:

    app: wordpress

  ports:

    - protocol: TCP

      port: 8080

      targetPort: 8080

      nodePort: 30000
---
apiVersion: v1

kind: Service

metadata:

  name: mariadb-service

spec:

  type: NodePort

  selector:

    app: mariadb

  ports:

    - protocol: TCP

      port: 3306

      targetPort: 3306
