apiVersion: v1
kind: Pod
metadata:
  name: mariadbpod
  labels:
    app: mariadb
spec:
  containers:
  - name: mariadb
    image: hngtech11/mariadb:latest
    ports:
    - containerPort: 3306

---
apiVersion: v1
kind: Service
metadata:
  name: mariadb-service
spec:
  type: NodePort
  selector:
    app: mariadb
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
